spring.application.name=Permission-of-lead
spring.datasource.url=jdbc:postgresql://localhost:5432/Lead
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sreelakshmy009@gmail.com
spring.mail.password=rmnv nzhq aufk ocho
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Allow slashes (/) in query parameters

server.tomcat.relaxed-query-chars=/