package com.project.Permission.of.lead.mapper;

import com.project.Permission.of.lead.dto.code.McodeDto;
import com.project.Permission.of.lead.dto.code.McodeValueDto;
import com.project.Permission.of.lead.entity.code.Mcode;
import com.project.Permission.of.lead.entity.code.McodeValue;
import com.project.Permission.of.lead.repository.code.McodeRepository;

import java.util.List;
import java.util.stream.Collectors;

public class McodeMapper {

    public static Mcode mapToMcode(McodeDto mcodeDto, McodeRepository repo) {
        Mcode parent = null;
        if (mcodeDto.getParentId() != null) {
            parent = repo.findById(mcodeDto.getParentId()).orElse(null);
        }

        return new Mcode(
                null, // id is generated by DB
                mcodeDto.getCodeName(),
                mcodeDto.isSystemDefault(),
                parent
        );
    }

    public static McodeDto mapToMcodeDto(Mcode mcode) {
        Long parentId = mcode.getParent() != null ? mcode.getParent().getId() : null;

        List<McodeValueDto> childrenDtos = null;
        if (mcode.getCodeValues() != null && !mcode.getCodeValues().isEmpty()) {
            childrenDtos = mcode.getCodeValues().stream()
                    .map(McodeMapper::mapToMcodeValueDto) // recursive call
                    .collect(Collectors.toList());
        }

        return new McodeDto(
                mcode.getId(),
                mcode.getCodeName(),
                mcode.isSystemDefault(),
                parentId,
                childrenDtos
        );
    }

    private static McodeValueDto mapToMcodeValueDto(McodeValue value) {
        return new McodeValueDto(
                value.getId(),                            // id
                value.isActive(),                         // isActive
                value.getCodeDescription(),               // codeDescription
                value.getCodeValue(),                     // codeValue
                value.isMandatory(),                      // isMandatory
                value.getOrderPosition(),                 // orderPosition
                value.getStoreValue(),                    // storeValue
                value.getParent() != null ? value.getParent().getId() : null, // parentId
                value.getCode() != null ? value.getCode().getId() : null      // codeId
        );
    }


}
